[package]
name = "jw-nvim"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.89"
nvim-oxi = { version = "0.5.1", features = ["neovim-0-10"] }
vibrato = "0.5.1"
zstd = "0.13.2"
